---
include:
  - board: nice_nano//zmk
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano//zmk
    shield: corne_right nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: xiao_ble//zmk
    shield: corne_dongle
